#!/bin/sh

CURR_DIR=`pwd`

cd $CURR_DIR/ys_proto
$CURR_DIR/make_all

cd $CURR_DIR/checkpoint_check
$CURR_DIR/make_all

cd $CURR_DIR/sndmsg
$CURR_DIR/make_all

cd $CURR_DIR/netlog
$CURR_DIR/make_all

# Commented out because build fails - missing library
#cd $CURR_DIR/ysrace
#$CURR_DIR/make_all

cd $CURR_DIR
