SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_C_COMPILER   i686-w64-mingw32-gcc)

SET(CMAKE_RC_COMPILER  i686-w64-mingw32-gcc)

SET(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)

# Define paths to search for libraries
SET(CMAKE_FIND_ROOT_PATH /usr/i686-w64-mingw32/)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# Don't search in native paths, just the specified root paths
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
